"""Scaffold client-owned files under ``client/`` (scripts, docs, CI, version pin)."""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from .models import DiscoveryReport, InstallParams

CLIENT_SCRIPTS = """\
#!/usr/bin/env bash
# Generated by diag init — start the diagnostic agent (Docker Compose).
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
AGENT="$ROOT/agent"
ENV_FILE="$AGENT/.env"

if ! command -v docker >/dev/null 2>&1; then
  echo "docker not found on PATH" >&2
  exit 1
fi
if [[ ! -f "$ENV_FILE" ]]; then
  if [[ -f "$AGENT/.env.example" ]]; then
    echo "Copy $AGENT/.env.example to $AGENT/.env first" >&2
  else
    echo "Missing $ENV_FILE" >&2
  fi
  exit 1
fi

if command -v diag >/dev/null 2>&1; then
  diag validate -w "$ROOT/workspace" || exit 1
fi

cd "$AGENT"
docker compose --env-file .env up -d --build

HOST_PORT="${AGENT_HOST_PORT:-8001}"
for _ in $(seq 1 30); do
  if curl -sf "http://127.0.0.1:${HOST_PORT}/health" >/dev/null 2>&1; then
    echo "Agent healthy at http://127.0.0.1:${HOST_PORT}/health"
    exit 0
  fi
  sleep 2
done
echo "Agent did not become healthy within 60s — check: docker compose logs" >&2
exit 1
"""

CLIENT_STOP = """\
#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT/agent"
docker compose --env-file .env down
echo "Agent stopped."
"""

CLIENT_STATUS = """\
#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT/agent"
docker compose --env-file .env ps
HOST_PORT="${AGENT_HOST_PORT:-8001}"
curl -sf "http://127.0.0.1:${HOST_PORT}/health" && echo || echo "health check failed"
"""

CLIENT_LOGS = """\
#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT/agent"
docker compose --env-file .env logs -f --tail=100 diagnostic-agent
"""

CLIENT_START_PS1 = """\
# Generated by diag init — start the diagnostic agent (Docker Compose).
$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$Agent = Join-Path $Root "agent"
$EnvFile = Join-Path $Agent ".env"

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    throw "docker not found on PATH"
}
if (-not (Test-Path $EnvFile)) {
    throw "Missing $EnvFile — copy agent/.env.example to agent/.env first"
}

if (Get-Command diag -ErrorAction SilentlyContinue) {
    & diag validate -w (Join-Path $Root "workspace")
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
}

Push-Location $Agent
try {
    docker compose --env-file .env up -d --build
    $port = 8001
    for ($i = 0; $i -lt 30; $i++) {
        try {
            $r = Invoke-WebRequest -Uri "http://127.0.0.1:$port/health" -UseBasicParsing -TimeoutSec 3
            if ($r.StatusCode -lt 400) {
                Write-Host "Agent healthy at http://127.0.0.1:$port/health"
                exit 0
            }
        } catch { Start-Sleep -Seconds 2 }
    }
    throw "Agent did not become healthy within 60s"
} finally {
    Pop-Location
}
"""

SYSTEMD_UNIT = """\
# Generated by diag init — standalone (non-Docker) agent service.
# Install: sudo cp diagnostic-agent.service /etc/systemd/system/
#          sudo systemctl daemon-reload && sudo systemctl enable --now diagnostic-agent
[Unit]
Description=Diagnostic Agent (diag serve)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=agent
WorkingDirectory={repo_root}
EnvironmentFile={client_dir}/agent/.env
Environment=AGENT_WORKSPACE={client_dir}/workspace
Environment=AGENT_PROFILE_DIR={client_dir}/workspace
Environment=AGENT_RUNBOOKS_PATH={client_dir}/workspace/runbooks
ExecStart=/usr/local/bin/diag serve --host 0.0.0.0 --port 8000
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
"""

CLIENT_CI = """\
# Client workspace validation (generated by diag init).
name: diagnostic-agent-client

on:
  push:
    paths:
      - 'client/**'
  pull_request:
    paths:
      - 'client/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install agent (editable)
        run: pip install -e .
      - name: Validate client workspace
        run: |
          diag validate -w client/workspace
          diag lint -w client/workspace
"""


def scaffold_client_extras(
    *,
    client_dir: Path,
    report: DiscoveryReport,
    params: InstallParams,
    upstream_version: str,
    repo_root: Path,
    dry_run: bool = False,
) -> list[Path]:
    """Write client-owned scripts, docs, CI, and upstream version marker."""
    written: list[Path] = []
    plan: list[tuple[Path, str, bool]] = [
        (client_dir / "scripts" / "start.sh", CLIENT_SCRIPTS, True),
        (client_dir / "scripts" / "stop.sh", CLIENT_STOP, True),
        (client_dir / "scripts" / "status.sh", CLIENT_STATUS, True),
        (client_dir / "scripts" / "logs.sh", CLIENT_LOGS, True),
        (client_dir / "scripts" / "start.ps1", CLIENT_START_PS1, False),
        (
            client_dir / "systemd" / "diagnostic-agent.service",
            SYSTEMD_UNIT.format(
                repo_root=str(repo_root.resolve()),
                client_dir=str(client_dir.resolve()),
            ),
            False,
        ),
        (client_dir / ".upstream-version", f"{upstream_version}\n", False),
        (client_dir / ".github" / "workflows" / "client-validate.yml", CLIENT_CI, False),
        (
            client_dir / "docs" / "OPERATIONS.md",
            _operations_md(report, params, upstream_version),
            False,
        ),
    ]

    for path, content, executable in plan:
        if dry_run:
            written.append(path)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
        if executable:
            path.chmod(0o755)
        written.append(path)
    return written


def _operations_md(
    report: DiscoveryReport, params: InstallParams, upstream_version: str
) -> str:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    tools = ", ".join(
        f"{t.kind.value} ({'OK' if t.reachable else 'missing'})"
        for t in sorted(report.tools, key=lambda x: x.kind.value)
    )
    return f"""\
# Client operations guide

Generated by `diag init` on {ts}.

## Upstream version

This deployment was scaffolded from upstream **{upstream_version}**.
Check with `diag upgrade` before merging new releases.

## Stack discovered

- Target: `{report.target}`
- Preset: `{params.preset}`
- Tools: {tools}
- Agent port: `{params.agent_host_port}`

## Daily commands

```bash
./client/scripts/start.sh
./client/scripts/stop.sh
./client/scripts/status.sh
./client/scripts/logs.sh
```

PowerShell: `.\\client\\scripts\\start.ps1`

## Customize

1. Edit `client/workspace/service_map.yaml` for your topology.
2. Replace runbooks under `client/workspace/runbooks/` with your own corpus.
3. Tune `client/agent/.env` (copy from `.env.example` if missing).
4. Merge `client/observability/` snippets into your live Prometheus/Loki stack.

## Updates

See [docs/CLIENT_FORK.md](../../docs/CLIENT_FORK.md) for `diag upgrade` and offline packs.
"""
