"""Emit workspace YAML with provenance headers and withheld candidates.

Files are assembled line by line rather than dumped from one dict, because a
draft has to interleave accepted values with commented-out ones. Individual
values still go through ``yaml.safe_dump`` so quoting and escaping are correct —
PromQL templates are full of braces and quotes.
"""
from __future__ import annotations

from typing import Any

import yaml

from .models import Candidate

INDENT = "  "


def scalar(value: Any) -> str:
    """Render one value as inline YAML (no trailing newline, no document marker)."""
    dumped = yaml.safe_dump(
        value, default_flow_style=True, sort_keys=False, width=10**6
    ).strip()
    if dumped.endswith("..."):
        dumped = dumped[:-3].strip()
    return dumped


def entry(key: str, value: Any, *, indent: int = 0) -> list[str]:
    """``key: value`` for a scalar, or a nested block for a mapping/sequence."""
    pad = INDENT * indent
    if isinstance(value, dict) and value:
        lines = [f"{pad}{key}:"]
        for sub_key, sub_value in value.items():
            lines.extend(entry(str(sub_key), sub_value, indent=indent + 1))
        return lines
    if isinstance(value, (list, tuple)) and value:
        lines = [f"{pad}{key}:"]
        for item in value:
            lines.append(f"{pad}{INDENT}- {scalar(item)}")
        return lines
    return [f"{pad}{key}: {scalar(value)}"]


def withheld(candidate: Candidate, *, indent: int = 0) -> list[str]:
    """A rejected candidate, commented out with the reason it was not written."""
    pad = INDENT * indent
    lines = [f"{pad}# {candidate.reason()}"]
    for line in entry(candidate.key, candidate.value, indent=indent):
        lines.append(f"# {line}" if not line.startswith("#") else line)
    return lines


def candidates_block(
    items: tuple[Candidate, ...], *, indent: int = 0
) -> list[str]:
    """Accepted candidates as YAML, withheld ones commented out beneath."""
    lines: list[str] = []
    for candidate in items:
        if candidate.accepted:
            lines.extend(entry(candidate.key, candidate.value, indent=indent))
        else:
            lines.extend(withheld(candidate, indent=indent))
    return lines


def section(key: str, items: tuple[Candidate, ...], *, indent: int = 0) -> list[str]:
    """A mapping key holding candidates, or nothing at all.

    Writing ``templates:`` with every entry commented out would parse as
    ``templates: null``, which *replaces* the preset's whole suite with nothing —
    a withheld candidate would silently disable working configuration. So a
    section with no accepted entries is emitted entirely inside comments.
    """
    if not items:
        return []
    pad = INDENT * indent
    if any(candidate.accepted for candidate in items):
        return [f"{pad}{key}:", *candidates_block(items, indent=indent + 1)]
    lines = [f"# {pad}{key}:"]
    for candidate in items:
        lines.append(f"# {pad}{INDENT}# {candidate.reason()}")
        for line in entry(candidate.key, candidate.value, indent=indent + 1):
            lines.append(f"# {line}")
    return lines


def header(
    title: str,
    *,
    purpose: str,
    usage: str,
    evidence: list[str],
    configure: str,
    has_withheld: bool = False,
) -> list[str]:
    """The comment block every drafted file opens with.

    Matches the shape ``diag install`` writes, with an EVIDENCE section so a
    reviewer can audit where each value came from.
    """
    lines = [
        f"# Generated by diag draft -- {title}.",
        "#",
        "# WHAT THIS FILE DOES",
        f"#   {purpose}",
        "#",
        "# HOW THE AGENT USES IT",
        f"#   {usage}",
        "#",
        "# EVIDENCE",
    ]
    for item in evidence or ["(none recorded)"]:
        lines.append(f"#   - {item}")
    if has_withheld:
        lines.extend(
            [
                "#",
                "# WITHHELD",
                "#   Commented-out entries below were proposed but not confirmed",
                "#   against the live stack. Each carries the reason. Uncomment only",
                "#   after checking the query yourself.",
            ]
        )
    lines.extend(
        [
            "#",
            "# CONFIGURE",
            f"#   {configure}",
            "#   Full reference: docs/WORKSPACE.md",
            "",
        ]
    )
    return lines


def document(header_lines: list[str], body: list[str]) -> str:
    text = "\n".join([*header_lines, *body])
    return text.rstrip("\n") + "\n"
